### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by michalbn** [esty6u/STORY-OF-LIFE#1]
Related Task
-Open group repository
-Meet up with the representatives of the science museum
-Write README File specified for the team project
-Open User Manual page in wiki
-Open Product page in wiki
-Open Team page in wiki
-Open Inception page in wiki
-Collaborate repository with Eran and Reuven

**Comment by robi-y** [comment]
Nice work, why do you have a sub task: "Meet up with the representatives of the science museum"?...

update the project description via repo. settings (it still say "A template repository with wiki for a team project at JCE's software engineering course")

Readme: hosting points to your chat!, remove or comment out badges that still point to jce-il/template-project
Inception: risks are very general, not project specific, a use case diagram in not optimal for discussing software structure, better use deployment or even class diagrams

Good luck!
