### ISSUE TITLE
Software Design Specification-SDS

### ISSUE THREAD

**Issue by esty6u** [esty6u/STORY-OF-LIFE#3]
-Main Goals
-Introduction Document Goals
-Main Product Features & Capabilities
-Related Documentation
-UML Modeling
-Deployment Diagrams
-Product Distribution
-CRC Cards & Class Diagrams
-Behaviour : Sequence and/or State Diagrams
-Persistence
-Non-functional Requirements
-Security

**Comment by eranhd** [comment]
great!
